version: "3.9"

services:

  webapp:
    build:
      args:
        MODE: production
    command: gunicorn --bind :8000 --workers 5 core.wsgi:application
    environment:
      - POSTGRES_ENGINE=${POSTGRES_ENGINE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - NSFW_API=${NSFW_API}

  nsfwjsapi:
    environment:
      - NODE_ENV=production

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - mediafiles:/webapp/core/mediafiles
    environment:
      ALLOWED_DOMAINS: ${SITE_URL}
      SITES: ${SITE_URL}=webapp:8000
    depends_on:
      - webapp
