name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - run: docker-compose -f docker-compose.yml -f docker-compose.production.yml build
      - run: docker-compose -f docker-compose.yml -f docker-compose.production.yml down --remove-orphans
      - run: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d
